// ぬりえを追加できる（＝データベースの category_id に入れてよい）カテゴリーIDの一覧。
// サーバー（src/worker.ts）の入力チェックが使う。画面の一覧は src/illustrations/illustrations.tsx の
// ILLUSTRATION_CATEGORIES から作られるので、カテゴリーを増やしたら、ここにも同じ id を足すこと
// （足し忘れると、画面には出るのに追加しようとすると失敗する）。
// 抜けがないかは `python3 scripts/check-categories.py` で確認できる。
export const LINEART_CATEGORY_IDS: ReadonlySet<string> = new Set([
  'ringo-mikan-lemon',
  'animals',
  'snacks',
  'flags',
  'signal-flags',
  'clothes',
  'home-things',
  'plants',
  'insects',
  'dinosaurs',
  'living-things',
  'birds',
  'fish',
  'patterns',
  'vehicles',
  'food',
  'tools',
  // 段階0で追加した「枠」（大カテゴリーごと）
  'amphibians',
  'weather',
  'space',
  'vegetables',
  'sweets',
  'trains',
  'airplanes',
  'ships',
  'rooms',
  'toys',
  'casual-wear',
  'world-costumes',
  'accessories',
  'patterns-asia',
  'patterns-europe',
  'patterns-africa',
  'patterns-america',
  'patterns-oceania',
  'road-signs',
  'safety-marks',
  'spring',
  'summer',
  'autumn',
  'winter',
  'fairies',
  'princesses',
  'monsters',
])
