// 日本の道路標識（警戒標識・規制標識）の一覧。
// page は public/lineart/road-signs/road-sign-{page}.png（線画）と
// public/lineart/road-signs-colored/road-sign-{page}.png（見本）の番号（標識番号。「_」は「-」に置き換え）。
// 出典: 国土交通省 道路標識一覧 https://www.mlit.go.jp/road/sign/sign/douro/ichiran.pdf
export const ROAD_SIGN_DATA = [
  // 警戒標識（けいかいひょうしき）
  { page: '201-A', title: '十字路交差点あり', subtitle: 'Crossroads ahead' },
  { page: '201-B', title: 'T字路交差点あり(えだ道)', subtitle: 'Side road junction ahead' },
  { page: '201-C', title: 'T字路交差点あり(つきあたり)', subtitle: 'T-junction ahead' },
  { page: '201-D', title: 'Y字路交差点あり', subtitle: 'Y-junction ahead' },
  { page: '201-2', title: 'ロータリーあり', subtitle: 'Roundabout ahead' },
  { page: '202', title: '右方屈曲あり', subtitle: 'Bend to the right' },
  { page: '203', title: '右方屈折あり', subtitle: 'Sharp bend to the right' },
  { page: '204', title: '右方背向屈曲あり', subtitle: 'S-shaped bend (right first)' },
  { page: '205', title: '右方背向屈折あり', subtitle: 'Sharp S-shaped bend (right first)' },
  { page: '206', title: '右つづら折りあり', subtitle: 'Winding road' },
  { page: '207-A', title: '踏切あり', subtitle: 'Railway crossing ahead' },
  { page: '207-B', title: '踏切あり(ふみきり2)', subtitle: 'Railway crossing ahead (2)' },
  { page: '208', title: '学校、幼稚園、保育所などあり', subtitle: 'School zone' },
  { page: '208-2', title: '信号機あり', subtitle: 'Traffic signal ahead' },
  { page: '209', title: 'すべりやすい', subtitle: 'Slippery road' },
  { page: '209-2', title: '落石のおそれあり', subtitle: 'Falling rocks' },
  { page: '209-3', title: '路面凹凸あり', subtitle: 'Bumpy road' },
  { page: '210', title: '合流交通あり', subtitle: 'Merging traffic' },
  { page: '211', title: '車線数減少', subtitle: 'Lane reduction' },
  { page: '212', title: '幅員減少', subtitle: 'Road narrows' },
  { page: '212-2', title: '二方向交通', subtitle: 'Two-way traffic' },
  { page: '212-3', title: '上り急勾配あり', subtitle: 'Steep hill upward' },
  { page: '212-4', title: '下り急勾配あり', subtitle: 'Steep hill downward' },
  { page: '213', title: '道路工事中', subtitle: 'Road work ahead' },
  { page: '214', title: '横風注意', subtitle: 'Crosswind area' },
  { page: '214-2', title: '動物が飛び出すおそれあり', subtitle: 'Animal crossing' },
  { page: '215', title: 'そのほかの危険', subtitle: 'Other dangers' },
  // 規制標識（きせいひょうしき）
  { page: '301', title: '通行止め', subtitle: 'No traffic' },
  { page: '302', title: '車両通行止め', subtitle: 'No vehicles' },
  { page: '303', title: '車両進入禁止', subtitle: 'No entry for vehicles' },
  { page: '304', title: '二輪の自動車以外の自動車通行止め', subtitle: 'No cars except motorcycles' },
  { page: '305-305-2', title: '大型貨物自動車等通行止め', subtitle: 'No large trucks' },
  { page: '306', title: '大型乗用自動車等通行止め', subtitle: 'No large buses' },
  { page: '307', title: '二輪の自動車・原動機付自転車通行止め', subtitle: 'No motorcycles or mopeds' },
  { page: '308', title: '自転車以外の軽車両通行止め', subtitle: 'No light vehicles except bicycles' },
  { page: '309', title: '自転車通行止め', subtitle: 'No bicycles' },
  { page: '310', title: '車両(組合せ)通行止め', subtitle: 'No specified vehicle combinations' },
  { page: '310-2', title: '二人乗り通行禁止', subtitle: 'No riding two on a motorcycle' },
  { page: '310-3', title: 'タイヤチェーン非装着車通行止め', subtitle: 'Tire chains required' },
  { page: '311-A', title: '指定方向外進行禁止(直進・左折)', subtitle: 'Directions only: straight or left' },
  { page: '311-B', title: '指定方向外進行禁止(左折)', subtitle: 'Direction only: left' },
  { page: '311-C', title: '指定方向外進行禁止(直進)', subtitle: 'Direction only: straight' },
  { page: '311-D', title: '指定方向外進行禁止(左折・右折)', subtitle: 'Directions only: left or right' },
  { page: '311-E', title: '指定方向外進行禁止(直進・左折・右折)', subtitle: 'Directions only: straight, left or right' },
  { page: '311-F', title: '指定方向外進行禁止(ななめ)', subtitle: 'Direction only: diagonal' },
  { page: '312', title: '車両横断禁止', subtitle: 'No vehicles crossing' },
  { page: '313', title: '転回禁止', subtitle: 'No U-turns' },
  { page: '314-314-2', title: '追越し禁止', subtitle: 'No overtaking' },
  { page: '315', title: '駐停車禁止', subtitle: 'No stopping or parking' },
  { page: '316-317', title: '駐車禁止', subtitle: 'No parking' },
  { page: '318', title: '時間制限駐車区間', subtitle: 'Time-limited parking zone' },
  { page: '319', title: '危険物積載車両通行止め', subtitle: 'No vehicles carrying dangerous goods' },
  { page: '320', title: '重量制限', subtitle: 'Weight limit' },
  { page: '321', title: '高さ制限', subtitle: 'Height limit' },
  { page: '322', title: '最大幅', subtitle: 'Width limit' },
  { page: '323-323-2', title: '最高速度', subtitle: 'Speed limit' },
  { page: '324', title: '最低速度', subtitle: 'Minimum speed' },
  { page: '325', title: '自動車専用', subtitle: 'Motor vehicles only' },
  { page: '325-2', title: '自転車専用', subtitle: 'Bicycles only' },
  { page: '325-3', title: '自転車及び歩行者専用', subtitle: 'Bicycles and pedestrians only' },
  { page: '325-4', title: '歩行者専用', subtitle: 'Pedestrians only' },
  { page: '325-5-A', title: '許可車両専用(バス)', subtitle: 'Authorized vehicles only (bus)' },
  { page: '325-5-B', title: '許可車両専用(タクシー)', subtitle: 'Authorized vehicles only (taxi)' },
  { page: '325-5-C', title: '許可車両専用(トラック)', subtitle: 'Authorized vehicles only (truck)' },
  { page: '325-6', title: '許可車両専用', subtitle: 'Authorized vehicles only' },
  { page: '325-7', title: '災害対策車両専用', subtitle: 'Disaster management vehicles only' },
  { page: '326-A', title: '一方通行', subtitle: 'One way' },
  { page: '326-B', title: '一方通行', subtitle: 'One way (vertical)' },
  { page: '326-2-A', title: '自転車一方通行', subtitle: 'One way for bicycles' },
  { page: '326-2-B', title: '自転車一方通行', subtitle: 'One way for bicycles (vertical)' },
  { page: '327', title: '車両通行区分', subtitle: 'Vehicle lane assignment' },
  { page: '327-2', title: '車両通行区分', subtitle: 'Vehicle lane assignment (2)' },
  { page: '327-3', title: '車両通行区分', subtitle: 'Vehicle lane assignment (3)' },
  { page: '327-4', title: '専用通行帯', subtitle: 'Reserved lane' },
  { page: '327-4-2', title: '普通自転車専用通行帯', subtitle: 'Bicycle reserved lane' },
  { page: '327-5', title: '路線バス等優先通行帯', subtitle: 'Bus priority lane' },
  { page: '327-6', title: '通行区分指定', subtitle: 'Lane designation' },
  { page: '327-7-A', title: '進行方向別通行区分(直進・左折・右折)', subtitle: 'Lane by direction: straight, left or right' },
  { page: '327-7-B', title: '進行方向別通行区分(直進・左折)', subtitle: 'Lane by direction: straight or left' },
  { page: '327-7-C', title: '進行方向別通行区分(左折)', subtitle: 'Lane by direction: left' },
  { page: '327-7-D', title: '進行方向別通行区分(直進)', subtitle: 'Lane by direction: straight' },
  { page: '327-8', title: '原動機付自転車の右折方法(二段階)', subtitle: 'Moped two-stage right turn' },
  { page: '327-9', title: '原動機付自転車の右折方法(小回り)', subtitle: 'Moped small right turn' },
  { page: '327-10', title: '環状交差点における右回り通行', subtitle: 'Clockwise travel at roundabout' },
  { page: '327-11', title: '平行駐車', subtitle: 'Parallel parking' },
  { page: '327-12', title: '直角駐車', subtitle: 'Right-angle parking' },
  { page: '327-13', title: '斜め駐車', subtitle: 'Angle parking' },
  { page: '328-328-2', title: '警笛鳴らせ', subtitle: 'Sound horn' },
  { page: '329-A-329-2-A', title: '徐行', subtitle: 'Slow down' },
  { page: '329-B-329-2-B', title: '徐行', subtitle: 'Slow down (vertical)' },
  { page: '330-A', title: '一時停止', subtitle: 'Stop' },
  { page: '330-B', title: '一時停止', subtitle: 'Stop (vertical)' },
  { page: '331', title: '歩行者通行止め', subtitle: 'No pedestrians' },
  { page: '332', title: '歩行者横断禁止', subtitle: 'No pedestrian crossing' },
]
