// 自動生成ファイル: scripts/generate-signal-flag-quiz-data.py で作成（手で編集しない）
// 国際信号旗クイズのパレット（正解色＋ダミー色）と合格ライン。キーは illustration の id。

import type { FlagQuizData } from './flagQuizData'

export const SIGNAL_FLAG_QUIZ_DATA: Record<string, FlagQuizData> = {
  'signal-flag-001': { passingScore: 88, swatches: [{ name: '白', hex: '#ffffff' }, { name: '青', hex: '#0000ff' }, { name: '紫', hex: '#af52de' }, { name: 'ピンク', hex: '#ff7ab8' }, { name: '茶色', hex: '#9b6330' }] },
  'signal-flag-002': { passingScore: 88, swatches: [{ name: '白', hex: '#ffffff' }, { name: '赤', hex: '#ff0000' }, { name: '緑', hex: '#1cb5a5' }, { name: 'ピンク', hex: '#ff7ab8' }, { name: '紫', hex: '#af52de' }] },
  'signal-flag-003': { passingScore: 88, swatches: [{ name: '白', hex: '#ffffff' }, { name: '青', hex: '#0000ff' }, { name: '赤', hex: '#ff0000' }, { name: '紫', hex: '#af52de' }, { name: 'ピンク', hex: '#ff7ab8' }] },
  'signal-flag-004': { passingScore: 88, swatches: [{ name: '白', hex: '#ffffff' }, { name: '青', hex: '#0000ff' }, { name: '黄', hex: '#ffff00' }, { name: 'ピンク', hex: '#ff7ab8' }, { name: '茶色', hex: '#9b6330' }] },
  'signal-flag-005': { passingScore: 88, swatches: [{ name: '白', hex: '#ffffff' }, { name: '青', hex: '#0000ff' }, { name: '赤', hex: '#ff0000' }, { name: '黄', hex: '#feb61c' }, { name: '緑', hex: '#1cb5a5' }] },
  'signal-flag-006': { passingScore: 88, swatches: [{ name: '白', hex: '#ffffff' }, { name: '赤', hex: '#ff0000' }, { name: '紫', hex: '#af52de' }, { name: '水色', hex: '#5bc8f2' }, { name: '緑', hex: '#1cb5a5' }] },
  'signal-flag-007': { passingScore: 88, swatches: [{ name: '白', hex: '#ffffff' }, { name: '青', hex: '#0000ff' }, { name: '黄', hex: '#ffff00' }, { name: 'ピンク', hex: '#ff7ab8' }, { name: '茶色', hex: '#9b6330' }] },
  'signal-flag-008': { passingScore: 88, swatches: [{ name: '白', hex: '#ffffff' }, { name: '赤', hex: '#ff0000' }, { name: '黄', hex: '#feb61c' }, { name: 'ピンク', hex: '#ff7ab8' }, { name: '茶色', hex: '#9b6330' }] },
  'signal-flag-009': { passingScore: 88, swatches: [{ name: '白', hex: '#ffffff' }, { name: '黄', hex: '#ffff00' }, { name: '黒', hex: '#000000' }, { name: '緑', hex: '#1cb5a5' }, { name: 'ピンク', hex: '#ff7ab8' }] },
  'signal-flag-010': { passingScore: 88, swatches: [{ name: '白', hex: '#ffffff' }, { name: '青', hex: '#0000ff' }, { name: '紫', hex: '#af52de' }, { name: '黄', hex: '#feb61c' }, { name: '茶色', hex: '#9b6330' }] },
  'signal-flag-011': { passingScore: 88, swatches: [{ name: '白', hex: '#ffffff' }, { name: '黄', hex: '#ffff00' }, { name: '青', hex: '#0000ff' }, { name: 'ピンク', hex: '#ff7ab8' }, { name: '赤', hex: '#ef6950' }] },
  'signal-flag-012': { passingScore: 88, swatches: [{ name: '白', hex: '#ffffff' }, { name: '黄', hex: '#ffff00' }, { name: '黒', hex: '#000000' }, { name: 'ピンク', hex: '#ff7ab8' }, { name: '赤', hex: '#ef6950' }] },
  'signal-flag-013': { passingScore: 88, swatches: [{ name: '白', hex: '#ffffff' }, { name: '青', hex: '#0000ff' }, { name: '緑', hex: '#1cb5a5' }, { name: '赤', hex: '#ef6950' }, { name: '黄', hex: '#feb61c' }] },
  'signal-flag-014': { passingScore: 88, swatches: [{ name: '白', hex: '#ffffff' }, { name: '青', hex: '#0000ff' }, { name: '水色', hex: '#5bc8f2' }, { name: '赤', hex: '#ef6950' }, { name: '茶色', hex: '#9b6330' }] },
  'signal-flag-015': { passingScore: 88, swatches: [{ name: '白', hex: '#ffffff' }, { name: '赤', hex: '#ff0000' }, { name: '黄', hex: '#ffff00' }, { name: '水色', hex: '#5bc8f2' }, { name: 'ピンク', hex: '#ff7ab8' }] },
  'signal-flag-016': { passingScore: 88, swatches: [{ name: '白', hex: '#ffffff' }, { name: '青', hex: '#0000ff' }, { name: '水色', hex: '#5bc8f2' }, { name: '赤', hex: '#ef6950' }, { name: 'オレンジ', hex: '#ff883e' }] },
  'signal-flag-017': { passingScore: 88, swatches: [{ name: '白', hex: '#ffffff' }, { name: '黄', hex: '#ffff00' }, { name: '緑', hex: '#1cb5a5' }, { name: '青', hex: '#29a2de' }, { name: '赤', hex: '#ef6950' }] },
  'signal-flag-018': { passingScore: 88, swatches: [{ name: '白', hex: '#ffffff' }, { name: '赤', hex: '#ff0000' }, { name: '黄', hex: '#ffff00' }, { name: 'ピンク', hex: '#ff7ab8' }, { name: '茶色', hex: '#9b6330' }] },
  'signal-flag-019': { passingScore: 88, swatches: [{ name: '白', hex: '#ffffff' }, { name: '青', hex: '#0000ff' }, { name: '水色', hex: '#5bc8f2' }, { name: '紫', hex: '#af52de' }, { name: 'ピンク', hex: '#ff7ab8' }] },
  'signal-flag-020': { passingScore: 88, swatches: [{ name: '白', hex: '#ffffff' }, { name: '赤', hex: '#ff0000' }, { name: '青', hex: '#0000ff' }, { name: '茶色', hex: '#9b6330' }, { name: '緑', hex: '#1cb5a5' }] },
  'signal-flag-021': { passingScore: 88, swatches: [{ name: '白', hex: '#ffffff' }, { name: '赤', hex: '#ff0000' }, { name: '青', hex: '#29a2de' }, { name: '茶色', hex: '#9b6330' }, { name: '水色', hex: '#5bc8f2' }] },
  'signal-flag-022': { passingScore: 88, swatches: [{ name: '白', hex: '#ffffff' }, { name: '赤', hex: '#ff0000' }, { name: '紫', hex: '#af52de' }, { name: 'ピンク', hex: '#ff7ab8' }, { name: '水色', hex: '#5bc8f2' }] },
  'signal-flag-023': { passingScore: 88, swatches: [{ name: '白', hex: '#ffffff' }, { name: '青', hex: '#0000ff' }, { name: '赤', hex: '#ff0000' }, { name: 'ピンク', hex: '#ff7ab8' }, { name: '紫', hex: '#af52de' }] },
  'signal-flag-024': { passingScore: 88, swatches: [{ name: '白', hex: '#ffffff' }, { name: '青', hex: '#0000ff' }, { name: '緑', hex: '#1cb5a5' }, { name: '赤', hex: '#ef6950' }, { name: '茶色', hex: '#9b6330' }] },
  'signal-flag-025': { passingScore: 88, swatches: [{ name: '白', hex: '#ffffff' }, { name: '黄', hex: '#ffff00' }, { name: '赤', hex: '#ff0000' }, { name: '紫', hex: '#af52de' }, { name: '水色', hex: '#5bc8f2' }] },
  'signal-flag-026': { passingScore: 88, swatches: [{ name: '白', hex: '#ffffff' }, { name: '黒', hex: '#000000' }, { name: '青', hex: '#0000ff' }, { name: '黄', hex: '#ffff00' }, { name: '赤', hex: '#ff0000' }, { name: 'ピンク', hex: '#ff7ab8' }, { name: '紫', hex: '#af52de' }] },
  'signal-flag-027': { passingScore: 88, swatches: [{ name: '白', hex: '#ffffff' }, { name: '黄', hex: '#ffff00' }, { name: '赤', hex: '#ff0000' }, { name: '緑', hex: '#1cb5a5' }, { name: 'ピンク', hex: '#ff7ab8' }] },
  'signal-flag-028': { passingScore: 88, swatches: [{ name: '白', hex: '#ffffff' }, { name: '赤', hex: '#ff0000' }, { name: '茶色', hex: '#9b6330' }, { name: '緑', hex: '#1cb5a5' }, { name: '紫', hex: '#af52de' }] },
  'signal-flag-029': { passingScore: 88, swatches: [{ name: '白', hex: '#ffffff' }, { name: '青', hex: '#0000ff' }, { name: '緑', hex: '#1cb5a5' }, { name: '茶色', hex: '#9b6330' }, { name: '赤', hex: '#ef6950' }] },
  'signal-flag-030': { passingScore: 88, swatches: [{ name: '白', hex: '#ffffff' }, { name: '赤', hex: '#ff0000' }, { name: '青', hex: '#0000ff' }, { name: '黄', hex: '#feb61c' }, { name: '紫', hex: '#af52de' }] },
  'signal-flag-031': { passingScore: 88, swatches: [{ name: '白', hex: '#ffffff' }, { name: '赤', hex: '#ff0000' }, { name: '黄', hex: '#feb61c' }, { name: '紫', hex: '#af52de' }, { name: 'ピンク', hex: '#ff7ab8' }] },
  'signal-flag-032': { passingScore: 88, swatches: [{ name: '白', hex: '#ffffff' }, { name: '黄', hex: '#ffff00' }, { name: '青', hex: '#0000ff' }, { name: 'オレンジ', hex: '#ff883e' }, { name: '紫', hex: '#af52de' }] },
  'signal-flag-033': { passingScore: 88, swatches: [{ name: '白', hex: '#ffffff' }, { name: '黒', hex: '#000000' }, { name: '赤', hex: '#ef6950' }, { name: 'オレンジ', hex: '#ff883e' }, { name: '紫', hex: '#af52de' }] },
  'signal-flag-034': { passingScore: 88, swatches: [{ name: '白', hex: '#ffffff' }, { name: '黄', hex: '#ffff00' }, { name: '赤', hex: '#ff0000' }, { name: '緑', hex: '#1cb5a5' }, { name: 'ピンク', hex: '#ff7ab8' }] },
  'signal-flag-035': { passingScore: 88, swatches: [{ name: '白', hex: '#ffffff' }, { name: '赤', hex: '#ff0000' }, { name: '緑', hex: '#1cb5a5' }, { name: '茶色', hex: '#9b6330' }, { name: '黄', hex: '#feb61c' }] },
  'signal-flag-036': { passingScore: 88, swatches: [{ name: '白', hex: '#ffffff' }, { name: '赤', hex: '#ff0000' }, { name: '黒', hex: '#000000' }, { name: '黄', hex: '#ffff00' }, { name: '青', hex: '#29a2de' }, { name: '緑', hex: '#1cb5a5' }] },
  'signal-flag-037': { passingScore: 88, swatches: [{ name: '白', hex: '#ffffff' }, { name: '青', hex: '#0000ff' }, { name: '黄', hex: '#ffff00' }, { name: 'オレンジ', hex: '#ff883e' }, { name: '水色', hex: '#5bc8f2' }] },
  'signal-flag-038': { passingScore: 88, swatches: [{ name: '白', hex: '#ffffff' }, { name: '水色', hex: '#6699ff' }, { name: '緑', hex: '#1cb5a5' }, { name: '黄', hex: '#feb61c' }, { name: 'オレンジ', hex: '#ff883e' }] },
  'signal-flag-039': { passingScore: 88, swatches: [{ name: '白', hex: '#ffffff' }, { name: '黒', hex: '#000000' }, { name: '黄', hex: '#feb61c' }, { name: '紫', hex: '#af52de' }, { name: 'ピンク', hex: '#ff7ab8' }] },
  'signal-flag-040': { passingScore: 88, swatches: [{ name: '白', hex: '#ffffff' }, { name: '赤', hex: '#ff0000' }, { name: '水色', hex: '#5bc8f2' }, { name: '紫', hex: '#af52de' }, { name: '緑', hex: '#1cb5a5' }] },
}
