// 国際信号旗（文字旗26枚・数字旗10枚・代表旗3枚・回答旗1枚）の一覧。
// page は public/lineart/signal-flags/signal-{page}.png（線画）と
// public/lineart/signal-flags-colored/signal-{page}.png（見本）の番号。
export const SIGNAL_FLAG_DATA = [
  { page: '001', title: 'A（アルファ）', subtitle: 'Alfa' },
  { page: '002', title: 'B（ブラボー）', subtitle: 'Bravo' },
  { page: '003', title: 'C（チャーリー）', subtitle: 'Charlie' },
  { page: '004', title: 'D（デルタ）', subtitle: 'Delta' },
  { page: '005', title: 'E（エコー）', subtitle: 'Echo' },
  { page: '006', title: 'F（フォックストロット）', subtitle: 'Foxtrot' },
  { page: '007', title: 'G（ゴルフ）', subtitle: 'Golf' },
  { page: '008', title: 'H（ホテル）', subtitle: 'Hotel' },
  { page: '009', title: 'I（インディア）', subtitle: 'India' },
  { page: '010', title: 'J（ジュリエット）', subtitle: 'Juliett' },
  { page: '011', title: 'K（キロ）', subtitle: 'Kilo' },
  { page: '012', title: 'L（リマ）', subtitle: 'Lima' },
  { page: '013', title: 'M（マイク）', subtitle: 'Mike' },
  { page: '014', title: 'N（ノベンバー）', subtitle: 'November' },
  { page: '015', title: 'O（オスカー）', subtitle: 'Oscar' },
  { page: '016', title: 'P（パパ）', subtitle: 'Papa' },
  { page: '017', title: 'Q（ケベック）', subtitle: 'Quebec' },
  { page: '018', title: 'R（ロミオ）', subtitle: 'Romeo' },
  { page: '019', title: 'S（シエラ）', subtitle: 'Sierra' },
  { page: '020', title: 'T（タンゴ）', subtitle: 'Tango' },
  { page: '021', title: 'U（ユニフォーム）', subtitle: 'Uniform' },
  { page: '022', title: 'V（ビクター）', subtitle: 'Victor' },
  { page: '023', title: 'W（ウイスキー）', subtitle: 'Whiskey' },
  { page: '024', title: 'X（エックスレイ）', subtitle: 'X-ray' },
  { page: '025', title: 'Y（ヤンキー）', subtitle: 'Yankee' },
  { page: '026', title: 'Z（ズールー）', subtitle: 'Zulu' },
  { page: '027', title: '0（ナダゼロ）', subtitle: 'Nadazero' },
  { page: '028', title: '1（ウナワン）', subtitle: 'Unaone' },
  { page: '029', title: '2（ビソトゥー）', subtitle: 'Bissotwo' },
  { page: '030', title: '3（テラスリー）', subtitle: 'Terrathree' },
  { page: '031', title: '4（カルテフォー）', subtitle: 'Kartefour' },
  { page: '032', title: '5（パンタファイブ）', subtitle: 'Pantafive' },
  { page: '033', title: '6（ソキシシックス）', subtitle: 'Soxisix' },
  { page: '034', title: '7（セッテセブン）', subtitle: 'Setteseven' },
  { page: '035', title: '8（オクトエイト）', subtitle: 'Oktoeight' },
  { page: '036', title: '9（ノベナイン）', subtitle: 'Novenine' },
  { page: '037', title: '第1代表旗', subtitle: 'First Substitute' },
  { page: '038', title: '第2代表旗', subtitle: 'Second Substitute' },
  { page: '039', title: '第3代表旗', subtitle: 'Third Substitute' },
  { page: '040', title: '回答旗', subtitle: 'Code / Answer' },
]
